language: java

# clone "travis" branch containing deployment settings
before_install: git clone -b travis `git config --get remote.origin.url` target/travis

# main build command with "mvn deploy"
script: mvn deploy --settings target/travis/settings.xml

# whitelist; only deploy master branch
branches:
  only:
  - master

env:
  global:
  - secure: ! 'I1K3zqkHI6M0Klrit5wHEeUAzU8cPorYU5JU94x1J1idNzNfGBCnsaJZj06D

      UYBxULjM0RluU4rHSQza6Bs3QT1ySUkOB2AdeoES+LnKWXgDej+LpTBfXgOL

      hXSZVzZkOYeAyhUmHPcmGCZdwONaPAs6200AUqtdTjjBr2bf7/U='
  - secure: ! 'AlNQ1TB+wJhHwp5ryOPSoUiQbDOa9F8HmpMi426DUulLydXQWmN7qntX3zSM

      fUoDT5KkPhAIpIhTxnehtjDbChTyGo+GvbEQ4jbuxitJwfWy6cGwG+U0qwll

      QobCQ4dz/yUGNxTC4F+H3q8nrrKqb0aQ0pjj5Aq31lgkjZT0DaU='
