language: java

# clone "travis" branch from DAISYs maven-parents repository containing deployment settings
before_install: git clone -b travis https://github.com/daisy-consortium/maven-parents.git target/travis

# main task, run the verify goal
script: mvn verify

# if the build succeeds, deploy the artifact (tests are skipped)
after_success: mvn deploy -DskipTests -Dinvoker.skip=true --settings target/travis/settings.xml

env:
  matrix:
  - secure: ! 'RpnGDXxMS1WenuTxM3IeoB/GnJZLheVnf71I6S1Fp3genqUtTHeDw6HIOVHt

      kmUfsMmY+mXy/CndRUlC+TXqYwiknxLDBkbO00kRbM/SY1dqCJulZCppnvDi

      2Nc+N0FlyiAjB8afYLp36pu7Nx6HRUjK9W+l3Hqax7dcqcFoWfo='
  - secure: ! 'UyWirx1c58WDWfsqU250Au+8n7YCqOzi6dzPNmSQSh8mT+StHVgq9Cv0SfZB

      PQpYc7DyUrohx8z7UNNdA1cykThGRJVfIbcFxqq20T75nBT+7MVrlxaUnyx3

      FiCHa5o6B6o8pg7jm4Xn/X27QHJAfZujx7yz0nj+NCM7tPSxmv4='

